all: overhead.cpp stopwatch.cpp
	g++ -DVERBOSE -o allcalls overhead.cpp stopwatch.cpp

task02: overhead.cpp stopwatch.cpp
	g++ -DTASK02 -o overhead overhead.cpp stopwatch.cpp

task03: overhead.cpp stopwatch.cpp
	g++ -DTASK03 -o casting overhead.cpp stopwatch.cpp

clean:
	rm allcalls overhead casting